apiVersion: v1
kind: Namespace
metadata:
  name: super-line
---
apiVersion: v1
kind: Service
metadata:
  name: super-line
  namespace: super-line
spec:
  selector:
    app: super-line-scaling-libp2p
  ports:
    - name: websocket
      port: 8801
      targetPort: websocket
---
apiVersion: v1
kind: Service
metadata:
  name: super-line-p2p
  namespace: super-line
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: super-line-scaling-libp2p
  ports:
    - name: libp2p
      port: 9001
      targetPort: libp2p
---
apiVersion: v1
kind: Service
metadata:
  name: super-line-control-center
  namespace: super-line
spec:
  selector:
    app: super-line-scaling-libp2p-control-center
  ports:
    - name: http
      port: 8091
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-line
  namespace: super-line
spec:
  replicas: 3
  selector:
    matchLabels:
      app: super-line-scaling-libp2p
  template:
    metadata:
      labels:
        app: super-line-scaling-libp2p
    spec:
      containers:
        - name: server
          image: super-line-scaling-libp2p:dev
          imagePullPolicy: Always
          command: [pnpm, --filter, "@super-line/example-scaling-libp2p", server]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PORT
              value: "8801"
            - name: P2P_PORT
              value: "9001"
            - name: P2P_DNS
              value: super-line-p2p.super-line.svc.cluster.local
            - name: PUBLISH_ANNOUNCEMENTS
              value: "true"
          ports:
            - name: websocket
              containerPort: 8801
            - name: libp2p
              containerPort: 9001
          readinessProbe:
            tcpSocket:
              port: websocket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-line-control-center
  namespace: super-line
spec:
  replicas: 1
  selector:
    matchLabels:
      app: super-line-scaling-libp2p-control-center
  template:
    metadata:
      labels:
        app: super-line-scaling-libp2p-control-center
    spec:
      containers:
        - name: control-center
          image: super-line-scaling-libp2p-control-center:dev
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8091
          readinessProbe:
            tcpSocket:
              port: http
